Categories
WildCodeSchool/2023-02-JS-Reims-project-3-adt pull request #22
Opened 2023-06-20 10:35 UTC by Rinawaticodes

2023-06-20 15:35 UTC, rocambille requested changes

2023-06-23 08:00 UTC, rocambille commented
it's nice to request a review, but you didn't chance anything after the feedbacks on this PR

2023-06-23 08:05 UTC, Rinawaticodes commented on backend/database.sql
> +("Responsabilité sociale", '/src/assets/images_icons/human.png') ;
i'm sorry, i did git pull instead git push.

2023-06-23 08:10 UTC, rocambille requested changes

2023-06-23 08:10 UTC, rocambille commented on frontend/src/components/Categories.jsx
> +      <figure>
a figure is a container for an image: remove this one

2023-07-05 07:19 UTC, rocambille requested changes

2023-07-05 07:19 UTC, rocambille commented on frontend/src/components/Categories.jsx
> +      <figure className="categories">
remove this line, and only this line

2023-07-05 07:19 UTC, rocambille commented on frontend/src/components/Categories.jsx
> +      </figure>
also remove this line, and only this line

2023-07-05 07:19 UTC, rocambille commented on frontend/src/components/Instruction.jsx
> +          to="/categories/:categoryId"
you must provide a value here for :categoryId. from the previous code, I guess you want to write:

    to="categories/hebergement"

2023-07-05 07:19 UTC, rocambille commented on frontend/src/components/Instruction.jsx
> +          to="/categories/Restaurant"
no upper case in urls

2023-07-05 07:19 UTC, rocambille commented on frontend/src/components/Instruction.jsx
> +          to="/categories/Guide"
no upper case in urls

2023-07-05 09:48 UTC, merged