S01 survey
WildCodeSchool/2023-02-JS-Reims-project-3-adt pull request #4
Opened 2023-06-01 08:45 UTC by khaliev

questions and styles addes

2023-06-01 12:08 UTC, rocambille requested changes

2023-06-01 12:08 UTC, rocambille commented on frontend/src/components/Navbar.css
> +  height: 10%;
remove fixed height

2023-06-01 12:08 UTC, rocambille commented on frontend/src/components/Navbar.css
> +  height: 10%;
same here

2023-06-01 12:08 UTC, rocambille commented on frontend/src/components/Obligatory.jsx
> +  return (
you should not have an Obligatory, Essential and an Optional component, but a Question component with a `type` prop

2023-06-06 12:25 UTC, Justine-Merlin commented
Still conflicts to resolve 👀

2023-06-06 13:42 UTC, closed without merging